name: CI

on:
  push:
    branches:
      - optimization
    tags:
      - '**'
  pull_request: {}

jobs:
  benchmark:
    name: run benchmarks
    runs-on: ubuntu-latest
    env:
      BENCHMARK_REPEATS: 1

    steps:
    - uses: actions/checkout@v2

    - name: set up python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: install and build
      run: |
        make install
        make build-cython
        pip install -r benchmarks/requirements.txt

    - run: make benchmark-pydantic
    - run: make benchmark-all
    - run: make benchmark-json